#!/usr/bin/env python3
"""Mulak Scout Intelligence Report - branded PDF, sent to Telegram."""
import os, requests
from datetime import datetime, timedelta
from dotenv import load_dotenv
from reportlab.lib.pagesizes import A4
from reportlab.lib.colors import HexColor, white
from reportlab.lib.units import mm
from reportlab.pdfgen import canvas

load_dotenv(os.path.expanduser("~/agents/scout/.env"))
SUPABASE_URL = os.environ["SUPABASE_URL"]
SERVICE_KEY  = os.environ["SUPABASE_SERVICE_ROLE_KEY"]
TG_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN")
TG_CHAT  = os.environ.get("TELEGRAM_CHAT_ID")
HEAD = {"apikey": SERVICE_KEY, "Authorization": f"Bearer {SERVICE_KEY}"}

# Brand
NAVY   = HexColor("#060A17")
NAVY2  = HexColor("#0B1120")
BLUE   = HexColor("#4F83F8")
BLUE2  = HexColor("#60A5FA")
GREEN  = HexColor("#34D399")
AMBER  = HexColor("#FBBF24")
RED    = HexColor("#F87171")
GRAY   = HexColor("#94A3B8")

KIND_META = {
    "meme":         ("MEME FORMAT", BLUE2),
    "video_format": ("VIDEO TREND", GREEN),
    "competitor":   ("COMPETITOR", RED),
    "market":       ("MARKET", AMBER),
}

W, H = A4

def fetch_trends(days=7):
    since = (datetime.utcnow() - timedelta(days=days)).isoformat()
    r = requests.get(
        f"{SUPABASE_URL}/rest/v1/trends", headers=HEAD,
        params={"found_at": f"gte.{since}", "order": "found_at.desc",
                "select": "kind,title,summary,source_url,relevance,found_at"},
    )
    return r.json()

def wrap(text, max_chars):
    words, lines, cur = (text or "").split(), [], ""
    for w_ in words:
        if len(cur) + len(w_) + 1 <= max_chars:
            cur = (cur + " " + w_).strip()
        else:
            lines.append(cur); cur = w_
    if cur: lines.append(cur)
    return lines

def rounded_card(c, x, y, w, h, fill, stroke=None):
    c.setFillColor(fill)
    if stroke:
        c.setStrokeColor(stroke); c.setLineWidth(0.8)
        c.roundRect(x, y, w, h, 4*mm, fill=1, stroke=1)
    else:
        c.roundRect(x, y, w, h, 4*mm, fill=1, stroke=0)

def cover(c, trends):
    c.setFillColor(NAVY); c.rect(0, 0, W, H, fill=1, stroke=0)
    # decorative circles
    c.setFillColor(NAVY2)
    c.circle(W-30*mm, H-20*mm, 60*mm, fill=1, stroke=0)
    c.circle(20*mm, 40*mm, 45*mm, fill=1, stroke=0)
    # brand mark
    c.setFillColor(BLUE); c.roundRect(25*mm, H-60*mm, 16*mm, 16*mm, 3*mm, fill=1, stroke=0)
    c.setFillColor(white); c.setFont("Helvetica-Bold", 14)
    c.drawCentredString(33*mm, H-54.5*mm, "M")
    c.setFont("Helvetica-Bold", 30)
    c.drawString(25*mm, H-80*mm, "Scout Intelligence")
    c.setFillColor(BLUE2); c.drawString(25*mm, H-92*mm, "Weekly Report")
    c.setFillColor(GRAY); c.setFont("Helvetica", 12)
    c.drawString(25*mm, H-104*mm, datetime.now().strftime("Week of %d %B %Y"))
    # KPI cards
    counts = {}
    for t in trends: counts[t["kind"]] = counts.get(t["kind"], 0) + 1
    cards = [("Total finds", str(len(trends)), BLUE),
             ("Memes / video", str(counts.get("meme",0)+counts.get("video_format",0)), GREEN),
             ("Competitor moves", str(counts.get("competitor",0)), RED),
             ("Market news", str(counts.get("market",0)), AMBER)]
    cw, ch, gap = 38*mm, 30*mm, 6*mm
    x0, y0 = 25*mm, H-160*mm
    for i, (label, val, col) in enumerate(cards):
        x = x0 + i*(cw+gap)
        rounded_card(c, x, y0, cw, ch, NAVY2, col)
        c.setFillColor(col); c.setFont("Helvetica-Bold", 22)
        c.drawCentredString(x+cw/2, y0+ch-13*mm, val)
        c.setFillColor(GRAY); c.setFont("Helvetica", 8)
        c.drawCentredString(x+cw/2, y0+6*mm, label)
    # bar chart: finds by kind
    c.setFillColor(white); c.setFont("Helvetica-Bold", 13)
    c.drawString(25*mm, y0-18*mm, "Finds by category")
    max_n = max(counts.values()) if counts else 1
    bx, by, bw_max = 25*mm, y0-70*mm, 120*mm
    order = ["meme","video_format","competitor","market"]
    for i, k in enumerate(order):
        n = counts.get(k, 0)
        label, col = KIND_META[k]
        yy = by + (3-i)*11*mm
        c.setFillColor(GRAY); c.setFont("Helvetica", 8)
        c.drawString(bx, yy+2.5*mm, label)
        bar_w = max(3*mm, bw_max * (n/max_n)) if n else 2*mm
        c.setFillColor(col if n else NAVY2)
        c.roundRect(bx+32*mm, yy, bar_w, 6*mm, 2*mm, fill=1, stroke=0)
        c.setFillColor(white); c.setFont("Helvetica-Bold", 9)
        c.drawString(bx+34*mm+bar_w, yy+1.5*mm, str(n))
    c.setFillColor(GRAY); c.setFont("Helvetica", 8)
    c.drawString(25*mm, 15*mm, "Mulak  ·  Ganaken  ·  generated by the Scout agent")
    c.showPage()

def trend_pages(c, trends):
    x, y = 20*mm, H-30*mm
    c.setFillColor(NAVY); c.rect(0, 0, W, H, fill=1, stroke=0)
    c.setFillColor(white); c.setFont("Helvetica-Bold", 18)
    c.drawString(x, y, "This week's intelligence")
    y -= 14*mm
    for t in trends:
        label, col = KIND_META.get(t["kind"], ("FIND", BLUE))
        sum_lines = wrap(t.get("summary") or "", 92)[:3]
        rel_lines = wrap("Mulak angle: " + (t.get("relevance") or "-"), 92)[:2]
        card_h = (16 + 5*len(sum_lines) + 5*len(rel_lines) + 8) * mm / 2.83  # pts→approx
        card_h = max(30*mm, min(card_h, 55*mm))
        if y - card_h < 20*mm:
            c.showPage()
            c.setFillColor(NAVY); c.rect(0, 0, W, H, fill=1, stroke=0)
            y = H-30*mm
        rounded_card(c, x, y-card_h, W-40*mm, card_h, NAVY2, col)
        # kind badge
        c.setFillColor(col); c.roundRect(x+5*mm, y-11*mm, 34*mm, 6*mm, 3*mm, fill=1, stroke=0)
        c.setFillColor(NAVY); c.setFont("Helvetica-Bold", 7)
        c.drawCentredString(x+22*mm, y-9*mm, label)
        # title
        c.setFillColor(white); c.setFont("Helvetica-Bold", 11)
        c.drawString(x+5*mm, y-18*mm, (t["title"] or "")[:80])
        yy = y-24*mm
        c.setFillColor(GRAY); c.setFont("Helvetica", 8.5)
        for ln in sum_lines:
            c.drawString(x+5*mm, yy, ln); yy -= 4.2*mm
        c.setFillColor(BLUE2); c.setFont("Helvetica-Oblique", 8.5)
        for ln in rel_lines:
            c.drawString(x+5*mm, yy, ln); yy -= 4.2*mm
        if t.get("source_url"):
            c.setFillColor(GRAY); c.setFont("Helvetica", 6.5)
            c.drawString(x+5*mm, y-card_h+4*mm, t["source_url"][:110])
        y -= card_h + 6*mm
    c.showPage()

def main():
    trends = fetch_trends()
    out = os.path.expanduser("~/agents/scout/scout-report.pdf")
    c = canvas.Canvas(out, pagesize=A4)
    cover(c, trends)
    if trends: trend_pages(c, trends)
    c.save()
    print("PDF:", out)
    if TG_TOKEN:
        with open(out, "rb") as f:
            requests.post(
                f"https://api.telegram.org/bot{TG_TOKEN}/sendDocument",
                data={"chat_id": TG_CHAT, "caption": "Scout: weekly intelligence report"},
                files={"document": ("mulak-scout-report.pdf", f, "application/pdf")},
                timeout=60,
            )
        print("Sent to Telegram.")

if __name__ == "__main__":
    main()
